[build]
  command = "npm install && npm run build && npm run server"
  publish = "out"
  functions = "functions"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[context.production.environment]
  NEXT_SERVERLESS = "true"
  NODE_ENV = "production"